
export enum ValidCharge {
    GERENTE = 'GERENTE',
    PRESIDENTE = 'PRESIDENTE',
    VICEPRESIDENTE = 'VICEPRESIDENTE',
    GERENTE_GENERAL = 'GERENTE GENERAL',
    AUDITOR_INTERNO = 'AUDITOR INTERNO',
    JURIDICO = 'CONSULTOR JURIDICO',
    GERENTE_DE_AREA = 'GERENTE DE AREA',
    GERENTE_DE_LINEA = 'GERENTE DE LINEA',
    COORDINADOR = 'COORDINADOR',
    PERSONAL_ADMINISTRATIVO = 'ANALISTA',
    OBRERO = 'OBRERO',
    PERSONAL_MEDICO = 'PERSONAL MEDICO',
    OFICIALES_DE_SEGURIDAD = 'OFICIAL DE SEGURIDAD',
    ESCOLTA = 'ESCOLTA',
    SUPERVISOR_DE_SEGURIDAD = 'SUPERVISOR DE SEGURIDAD',
    OTRO = 'OTRO'
}